- hosts: all
  vars:
    project: letsresume
    project_dir: /home/bhirbec/{{ project }}
    app_dir: "{{ project_dir }}/app"

  tasks:

    - name: Sync files
      synchronize:
        src: "../{{ item }}"
        dest: "{{ project_dir }}"
        recursive: yes
        delete: yes
      with_items:
        - app

    - name: Install React App Packages
      npm:
        path: "{{ app_dir }}"
        state: present

    - name: Install React App Packages
      npm:
        path: "{{ app_dir }}/server"
        state: present

    - name: Running postinstall Script
      shell: make postinstall chdir={{app_dir}}

    - name: Build React App
      shell: make js chdir={{app_dir}}

    - name: Copy upstart conf
      template: src=upstart.conf dest=/etc/init/letsresume.conf
      sudo: yes

    - name: Restart web service
      command: service letsresume restart
      sudo: yes

